### ISSUE TITLE
Error during install due to setuptools "use_2to3" 

### ISSUE THREAD

**Issue by brlogan** [trustar/trustar-sdk2-proto#65]
The setuptools library deprecated "use_2to3" with v46.2.0 in May of 2020.
Support for 2to3 was subsequently removed in v58.0.0 in September of 2021.
The most recent version of setuptools is v62.1.0.

Upon install using `pip install trustar2`, if the user has setuptools v58.0.0. or newer, install will fail with the following error:
```
Collecting trustar2
  Downloading trustar2-0.7.5.tar.gz (39 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /<REDACTED>/lib/python3.9/site-packages/setuptools/dist.py:739: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      error in trustar2 setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

User must downgrade to setuptools v57.5.0 or earlier to successfully install.

Official Recommendation:

> [#2086](https://github.com/pypa/setuptools/issues/2086): Removed support for 2to3 during builds. Projects should port to a unified codebase or pin to an older version of Setuptools using [PEP 518](https://www.python.org/dev/peps/pep-0518/) build-requires.

**Comment by dsolmirano** [comment]
Just merged an update - we no longer use2_to_3
